version: '3.8'
services:
  test-runner:
    build: .
    volumes:
      - ./screenshots:/app/screenshots
    depends_on:
      - mock-api
  mock-api:
    build:
      context: ..            # This tells it to look at the Root
      dockerfile: docker/Dockerfile
    image: kennethreitz/httpbin
    ports:
      - "8080:80"