version: '3.8'
services:
  test-runner:
    build:
      context: ..                          # ‚Üê this is the key fix
      dockerfile: docker/Dockerfile  
    volumes:
      - ./screenshots:/app/screenshots
    depends_on:
      - mock-api
  mock-api:
    build:
      context: ..            # This tells it to look at the Root
      dockerfile: docker/Dockerfile
    image: kennethreitz/httpbin
    ports:
      - "8080:80"