name: SDET matrix CI/CD
on: [push, pull_request]

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.11','3.12']  
        browser: ['chromium','firefox']
        os: [windows-latest, ubuntu-latest]
        exclude:
          - os: windows-latest
            browser: firefox
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
       python-version: ${{ matrix.python-version }}

    - name: Install and Playwright
      run: |
        pip install -r requirements.txt
    - name: Install Playwright Browsers
      run: playwright install ${{ matrix.browser }}

    - name: Install System Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libgbm-dev libnss3 libasound2

    - name: Install Playwright Browsers
      run: playwright install ${{ matrix.browser }}
        
    - name: Run Tests
      run: pytest tests/ -v --cov=dsa

    - name: Docker
      run: |
        docker build -t matrix-tests .
        docker run --rm matrix-tests
    

