name: SDET matrix CI/CD
on: [push, pull_request]

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']  
        browser: ['chromium','firefox']
        os: [windows-latest, ubuntu-latest]
        exclude:
          - os: windows-latest
            browser: firefox
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
       python-version: ${{ matrix.python-version }}

    - name: Install and Playwright
      run: pip install -r requirements.txt

    - name: Install Playwright Browsers (Linux)
      if: runner.os == 'Linux'
      run: playwright install --with-deps ${{ matrix.browser }}

    - name: Install Playwright Browsers (Windows)
      if: runner.os == 'Windows'
      run: playwright install ${{ matrix.browser }}
           
    - name: Run Tests
      run: pytest tests/ -v --cov=dsa

    - name: Docker
      run: |
        docker build -t matrix-tests .
        docker run --rm matrix-tests
    

